FROM node:18

WORKDIR /app

COPY package*.json .
COPY packages/common/package*.json ./packages/common/
COPY packages/api/package*.json ./packages/api/
COPY packages/client/package*.json ./packages/client/

RUN npm install

COPY . .

RUN npm run build -w @tspark/common
